source 'https://rubygems.org'

gem 'pry'
gem 'rake', '~> 13.0', '>= 13.0.6'
gem 'rack-test'
gem 'rspec'
gem 'rack-cors'
gem 'shotgun'
gem "require_all"
gem "activerecord", "~> 5.2"
gem "sinatra-activerecord"
gem 'faker'
gem 'sqlite3'
gem 'railties' 
gem 'pg'
gem 'nokogiri', '~> 1.12', '>= 1.12.3'
gem 'rails'